### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by filipwiech** [bartwronski/CSharpRenderer#4]
It seems that after the latest update a memory leak has been introduced - during application runtime new memory is constantly being allocated (until system runs of out it).

**Comment by bartwronski** [comment]
Hi, in general the framework doesn't handle dx resource release at all - but if this is a new issue I will have a look at it today later.

**Comment by filipwiech** [comment]
Oh right, it seems that I have fixed the issue. It is connected with Lua usage. In file ConstantBuffer.cs in method CompileAndBind() you need to close Lua context after using it (luaContext.Close()), otherwise it will grow indefinetly. Also I was wrong, this issue exists in earlier versions as well, sorry.

// Execute!
                luaContext.DoString(m_Definition.m_Script);

```
            foreach (var scriptedProperty in scriptedProperties)
            {
                m_Writer.Seek(scriptedProperty.byteOffset, SeekOrigin.Begin);
                CustomConstantBufferDefinition.ConstantType type = scriptedProperty.type;
                float value = (float)(double)luaContext[scriptedProperty.name];

                BufferWriteType(type, value);
            }

            luaContext.Close(); // Close Lua context
        }
```

**Comment by bartwronski** [comment]
Yes, I found it as well. I will use IDisposable pattern that lua context supports. :) 
using (Lua luaContext = new Lua()) ...
I found 2 other simple errors - constant buffers are recreated every frame and Scene.cs uses wrong frame number after refactor. I will submit all today after 6PM EST.
Thanks!

**Comment by filipwiech** [comment]
No problem and thanks as well. :)
Just wanted to let you know it's really great you share this code and I can't wait for some further improvements and additions, like screen space reflections. ;) Keep up the good work!

**Comment by bartwronski** [comment]
Thanks, I'm very happy that you find it useful. :) 
Screenspace reflections + cubemaps come next (in max couple weeks) so stay tuned.
I submitted the fix + couple other minor fixes - thanks again for pointing it out!
